### ISSUE TITLE
`parseResouce` does not support second argument

### ISSUE THREAD

**Issue by smalluban** [mykulyak/json-api#27]
https://github.com/mykulyak/json-api/blob/80a07a90cf1a8a5b0aefc18dd40655e445ca7dd8/src/Registry.js#L57

It will break if `includesMap` will be passed to `parseResource()` .

**Comment by smalluban** [comment]
Ok, I found `includesMap` variable in upper scope ;)

**Comment by mykulyak** [comment]
Fixed.
